<div>
    <form name="issueForm" action="/issue" method="post" class="form-horizontal well" onsubmit="">

              <div class="form-group">
                   <label for="bookId" class="col-lg-2 control-label">Book Id:</label>
                   <div class="col-lg-4">
                      <input type="text" class="form-control" id="bookId" name="bookId"/>
                   </div>
              </div>

       <div class="form-group">
                          <div class="col-lg-2"></div>
                          <div class="col-lg-4">
                <button type="submit" class="btn btn-primary">IssueBook</button>
                          </div>
                     </div>

    </form>

</div>