<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>


        <script src="/public/js/form.js"></script>
        <script src="/public/js/jquery.js"></script>



</head>
<body>
    <div class="header">$partials/header()$</div>

    <div class="body">$body$</div>

    <div class="footer">
        <div class="center-alignment">$partials/footer()$</div>
    </div>
</body>
</html>