<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <script src="/public/js/form.js"></script>
    <script src="/public/js/jquery.js"></script>
    <script src="/public/js/validation.js"></script>
    <link href="/public/css/bootstrap.css" rel="stylesheet" type="text/css"></link>
    <link href="/public/css/bootstrap.min.css" rel="stylesheet" type="text/css"></link>
    <link href="/public/css/main.css" rel="stylesheet" type="text/css"></link>

</head>
<body>
    <div class="header">$partials/header()$</div>
    <div class="row-fluid">
        <div class="span2 sidebar">$partials/sidebar()$</div>
        <div class="span8 content">
            <div>$body$</div>
        </div>
    <div class="footer">$partials/footer()$</div>
</body>
</html>